package com.example.brickx.entities.enums;

public enum JobType {
    MANAGER, COSTMANAGER, INSPECTOR, FLOORINGINSTALLER, SURVEYOR, BRICKMASON, IRONWORKER, CRANEOPERATOR, SAFETYMANAGER, COSTESTIMATOR,
}
